### ISSUE TITLE
zipkin not working for web requests?

### ISSUE THREAD

**Issue by anildigital** [openzipkin/zipkin-ruby#111]
Hi,

I have created a sample Rails application with CRUD for users.

I have added `zipkin-tracer` Ruby gem to Gemfile and done configuration config.ru 

But I don't see any traces available at my locally running Zipkin instance http://localhost:9411/zipkin/

Am I missing anything?

Thanks

**Comment by jcarres-mdsol** [comment]
Must be a configuration problem, the gem is working in production and also in local setups like the one you describe

**Comment by anildigital** [comment]
Thanks. Actually it got resolved. I did not press "Find Traces" button and kept refreshing the page.

**Comment by jcarres-mdsol** [comment]
Thanks, closing
