### ISSUE TITLE
Should omit ParentSpanId header for root spans

### ISSUE THREAD

**Issue by sullerandras** [openzipkin/zipkin-ruby#115]
There are services which throw error when an empty `X-B3-ParentSpanId` header sent with the HTTP request.

From the [openzipkin specification](https://github.com/openzipkin/b3-propagation#parentspanid-1):

> The `X-B3-ParentSpanId` header must be present on a child span and absent on the root span.

## How to reproduce

```ruby
conn = Faraday.new() do |faraday|
  faraday.use ZipkinTracer::FaradayHandler, 'service_name'
  faraday.request :url_encoded
  faraday.adapter Faraday.default_adapter
end
conn.get('http://logs-01.loggly.com/inputs/TOKEN/tag/http/')
```

Result is `400 Bad request`.

If we don't send tracing headers, the response is the expected `403 Invalid API key`:
```ruby
conn = Faraday.new() do |faraday|
  faraday.request :url_encoded
  faraday.adapter Faraday.default_adapter
end
conn.get('http://logs-01.loggly.com/inputs/TOKEN/tag/http/')
```

## Workaround

The only workaround i found so far is to monkey patch FaradayHandler with `unless trace_id.send(method).to_s.empty?` as below:

```ruby
require 'zipkin-tracer/faraday/zipkin-tracer'
module ZipkinTracer
  class FaradayHandler < ::Faraday::Middleware
    def call(env)
      trace_id = TraceGenerator.new.next_trace_id
      TraceContainer.with_trace_id(trace_id) do
        b3_headers.each do |method, header|
          env[:request_headers][header] = trace_id.send(method).to_s unless trace_id.send(method).to_s.empty?
        end
        if Trace.tracer && trace_id.sampled?
          trace!(env, trace_id)
        else
          @app.call(env)
        end
      end
    end
  end
end
```

**Comment by adriancole** [comment]
Closed as not an issue?

**Comment by sullerandras** [comment]
I don't think I closed this. This is definitely an issue. Please reopen it.
