### ISSUE TITLE
log the "sa" annotation when making outbound calls

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-ruby#22]
The rack zipkin tracer collects the local endpoint, which allows it to indicate the correct host when adding annotations.

``` ruby
::Trace.default_endpoint = ::Trace.default_endpoint.with_service_name(config.service_name).with_port(config.service_port)
--snip--
::Trace.record(::Trace::Annotation.new(::Trace::Annotation::SERVER_RECV, ::Trace.default_endpoint))
```

When making outbound calls, the faraday code uses the server address as the endpoint for all annotations, including http.uri, http.status, CLIENT_SEND, and CLIENT_RECV. This is incorrect as the actual log statements (annotations) are made from the client. For example, when instrumented, the server may record a different `http.uri` for the same span, due to rewriting, and also the server may send a correct status back, which the client doesn't receive. It is important to log the local host within annotations, as otherwise debugging becomes misdirected.

The correction would be to change the faraday `ZipkinTracer` to log its local visible IP (in docker, usually this is the container IP).

In order to indicate the recipient, when recording CLIENT_SEND and http.uri, also record SERVER_ADDR with the value of a single byte 1 (not ASCII '1', which is 49). I'm not sure the exact syntax, but here's what it might look like.

``` ruby
record(::Trace::BinaryAnnotation.new(::Trace::Annotation::SERVER_ADDR, [1], "BOOL", endpoint))
```

**Comment by jcarres-mdsol** [comment]
We do V2 now, issue not valid anymore
