### ISSUE TITLE
Boolean representation for HTTP_X_B3_SAMPLED incorrect resulting in broken traces

### ISSUE THREAD

**Issue by singram** [openzipkin/zipkin-ruby#68]
Zipkin-tracer current interprets boolean on HTTP_X_B3_SAMPLED as 'true' or 'false'.

This is out of sync with the header specification and other zipkin tracing interpretations (spring-sleuth/ zipkin-js etc).  Outside of the library implementations themselves the only specification I could find for the headers was here https://twitter.github.io/zipkin/Instrumenting.html#communicating-trace-information

The end effect is that so long as your micro-service ecosystem exclusively uses zipkin-tracer everything is ok but as soon as you start to work in a polyglot ecosystem traces get dropped due to inconsistent interpretation of this header on the inbound and incorrect setting on outbound calls.

Proposal
- Change the interpretation of 'HTTP_X_B3_SAMPLED' to be '0'/'1' inline with specification and other implementations.

**Comment by pavolloffay** [comment]
+1 for solving it.

**Comment by jcarres-mdsol** [comment]
Since #79  this should be fixed

**Comment by pavolloffay** [comment]
@jcarres-mdsol thanks for solving it!
