### ISSUE TITLE
Parent span ID header should be optional

### ISSUE THREAD

**Issue by rgueldem** [openzipkin/zipkin-ruby#87]
We are using the zipkin tracer rack middleware and it doesn't properly handle requests that have a trace ID, span ID and sampled flag but no parent span ID. According to the documentation, the parent span ID should be fully optional.

https://github.com/openzipkin/zipkin-ruby/blob/master/lib/zipkin-tracer/rack/zipkin-tracer.rb#L24 lists the `X-B3-ParentSpanID` header as required, which will fail the `called_with_zipkin_headers?` check. Moving it to the optional headers should fix it, but will break the order in `trace_parameters`.

**Comment by adriancole** [comment]
PS the context of this is that there are debugging tools such as the chrome
plugin who control the trace and span id of the root by propagating them
(usually they also set flags=1 and sampled=1 to ensure the trace is saved).
In this case, there's no parent span id. So when a parent span id wasn't
propagated, we indicate this is the root span with an externally
provisioned ID.

**Comment by rgueldem** [comment]
If it helps, this is the fix I use locally:
```diff
diff --git a/lib/zipkin-tracer/rack/zipkin-tracer.rb b/lib/zipkin-tracer/rack/zipkin-tracer.rb
index 7552522..d7af5c5 100644
--- a/lib/zipkin-tracer/rack/zipkin-tracer.rb
+++ b/lib/zipkin-tracer/rack/zipkin-tracer.rb
@@ -21,8 +21,8 @@ module ZipkinTracer
   # This middleware reads Zipkin headers from the request and sets/creates a Trace.id usable by the rest of the app
   # It will also send the trace to the Zipkin service using one of the methods configured.
   class RackHandler
-    B3_REQUIRED_HEADERS = %w[HTTP_X_B3_TRACEID HTTP_X_B3_PARENTSPANID HTTP_X_B3_SPANID HTTP_X_B3_SAMPLED].freeze
-    B3_OPT_HEADERS = %w[HTTP_X_B3_FLAGS].freeze
+    B3_REQUIRED_HEADERS = %w[HTTP_X_B3_TRACEID HTTP_X_B3_SPANID HTTP_X_B3_SAMPLED].freeze
+    B3_OPT_HEADERS = %w[HTTP_X_B3_PARENTSPANID HTTP_X_B3_FLAGS].freeze
 
     def initialize(app, config = nil)
       @app = app
@@ -79,13 +79,13 @@ def trace_id(default_flags = Trace::Flags::EMPTY)
                              @env.values_at(*B3_REQUIRED_HEADERS)
                            else
                              new_id = Trace.generate_id
-                             [new_id, nil, new_id]
+                             [new_id, new_id]
                            end
-        trace_parameters[3] = should_trace?(trace_parameters[3])
+        trace_parameters[2] = should_trace?(trace_parameters[2])
         trace_parameters += @env.values_at(*B3_OPT_HEADERS) # always check flags
         trace_parameters[4] = (trace_parameters[4] || default_flags).to_i
 
-        Trace::TraceId.new(*trace_parameters)
+        Trace::TraceId.new(trace_parameters[0], trace_parameters[3], trace_parameters[1], trace_parameters[2], trace_parameters[4])
       end
 
       def called_with_zipkin_headers?
@@ -104,7 +104,7 @@ def current_trace_sampled?
 
       def should_trace?(parent_trace_sampled)
         if parent_trace_sampled  # A service upstream decided this goes in all the way
-          parent_trace_sampled == 'true'
+          ['1', 'true'].include? parent_trace_sampled
         else
           force_sample? || current_trace_sampled? && !filtered?
         end
```

**Comment by adriancole** [comment]
thanks for the spike.

one note: HTTP_X_B3_SAMPLED isn't required. When unset, the receiver still
uses the ids, just it needs to make the decision locally as to whether to
trace or not (based on the propagated trace id)

**Comment by jcarres-mdsol** [comment]
I did not know about those headers being optional as per spec. We will need to change this.

Should be easy to change it. I worry about the system become more difficult to reason about. Now you kind of know things have to be a certain way. With such flexibility and local decisions, it will be complex to debug issues as things may be missing or locally generated, etc.

**Comment by adriancole** [comment]
I agree it seems to be more flexible, but if you think of it this way, the
headers tell you which span ids to use, right? That part hasn't changed.

So, being told the ids of a root span is pretty much the same idea as being
told the ids of a child span. In the root span, there's no parent. You
don't generate more in either case, rather trust what's given to you.

Not sure, but maybe this makes it simpler to understand.

**Comment by jcarres-mdsol** [comment]
This was solved years ago, closing the PR
